### ISSUE TITLE
Swagger input data in application/content-type format are not OK

### ISSUE THREAD

**Issue by gdchamal** [CaliOpen/Caliopen#102]
Currently definition of input data suppose to have formData values and not json content type.

We must change the swagger spec to support only json as input data.

**Comment by iamdey** [comment]
it can be both for dev purpose, may be (if swagger doesn't support json)?

**Comment by sapiens-sapide** [comment]
On which route do you see that ?
I set a json content body on route PATH /contacts/{id} in swagger definition for example.

**Comment by iamdey** [comment]
Authentications

**Comment by gdchamal** [comment]
It's about input data, usin json content type and payload on POST /authentications fail with such error:

```
"{"errors": [{
"code": 400, 
"description": "The server could not comply with the request since it is either malformed or otherwise incorrect.", 
"component": "Unknown", 
"values": 400, 
"message": "username is a required parameter.

Failed validating u'required' in schema:
    {u'in': u'formData',
         u'name': u'username',
              u'required': True,
                   u'type': u'string'}

On instance:
    None", "property": "RequestValidationError", "type": "Bad Request"}]}"
```

**Comment by gdchamal** [comment]
Using swagger in=body for parameter input with a schema reference object works, but I found that we don't get value on request.swagger_data and must use request.json property.

Apparently many impacts on API, but maybe I didn't experiment correctly. We'll discuss that tomorrow

**Comment by sapiens-sapide** [comment]
you missed something chamal, I get the json body from swagger_data on route PATH. See you tomorrow.

**Comment by gdchamal** [comment]
fixed with https://github.com/CaliOpen/Caliopen/pull/103
