### ISSUE TITLE
When adding a remote identity, should add it to user contact

### ISSUE THREAD

**Issue by gdchamal** [CaliOpen/Caliopen#1088]
When adding a remote identity to an user, if this identity is not yet present on his own contact, we should add it

@sapiens-sapide WDYT ?

**Comment by sapiens-sapide** [comment]
yes, it makes sense

**Comment by sapiens-sapide** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Auto-add remote identity to user's contact](https://trello.com/c/075BPTi0/182-auto-add-remote-identity-to-users-contact)
