### ISSUE TITLE
PI for sent mail

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#1107]
PI is not yet evaluated for sent mails.

---

cf #1099 

![pi](https://user-images.githubusercontent.com/1287627/48899031-b10bcb00-ee4e-11e8-979f-1d1891eb9aff.png)

this happens when pi property is missing in message.

**Comment by sapiens-sapide** [comment]
PI is not yet computed on sent mail. Is it OK for frontend if backend returns an empty value ?
```json
{
  "pi": null
}
```
or 
```json
{
  "pi": {}
}
```

**Comment by sapiens-sapide** [comment]
OK, so _you_ close ticket when ready ?

**Comment by iamdey** [comment]
_reword as a missing feature_

**Comment by iamdey** [comment]
sent mail has now a PI
