### ISSUE TITLE
which property to display for last check date on remotes

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#1125]
there's is 2 properties available to display:

```
{ last_check: "xxx", infos: { lastsync: "yyy" } }
```

be aware that for twitter and standard imap, `last_check` is undefined, ok with gmail (on my alpha account)

What property the client should display ?

**Comment by sapiens-sapide** [comment]
I'll make sure that `last_check` is allways updated, thus frontend must use this property in UI to display  « dernière connexion » date/time. Be aware that `last_check` doesn't mean that connexion was successfull.

**Comment by iamdey** [comment]
perfect, `last_check` is used actually

**Comment by sapiens-sapide** [comment]
hot fix in develop with commits #ea79ada2, #a1f58295 and #eefa75f2
