### ISSUE TITLE
PATCH password error 401

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#1132]
on alpha & dev : 

```
// PATCH http://localhost:4000/api/v2/users/63f3de8b-3468-4b1b-8784-2cf89763c594
{"password":"654321","current_state":{"password":"123456"}}

// Status Code: 401 Unauthorized
// empty response
```

cf. https://feedback.caliopen.org/t/mise-a-jour-du-mot-de-passe/606

**Comment by sapiens-sapide** [comment]
are you sure to send required headers on these route ? (`X-Caliopen-Device-Id` and `X-Caliopen-Device-Signature`)
