### ISSUE TITLE
I can't sign up

### ISSUE THREAD

**Issue by floriancuerq** [CaliOpen/Caliopen#1188]
Hello,
Every time I try to sign up I got this message 

> Impossible de créer un compte. Merci d'essayer à nouveau ou de contacter un administrateur.

Evenif I change the invitation email with something else than my personnal email.

Thanks for your time

**Comment by floriancuerq** [comment]
> Hello,
> Every time I try to sign up I got this message
> 
> > Impossible de créer un compte. Merci d'essayer à nouveau ou de contacter un administrateur.
> 
> Evenif I change the invitation email with something else than my personnal email.
> 
> Thanks for your time

**Comment by iamdey** [comment]
we were in the rush (and still on it).
Did you managed to create an account?

We recently had new accounts created and no specific errors.

**Comment by floriancuerq** [comment]
@iamdey  Yes, I wait a few day and now I can connect to my caliopen account with no problem.
