### ISSUE TITLE
unable to connect remote idents

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#1201]
in dev branch, I try to create a remote twitter or gmail. Allowing the app is OK but when the callback is called, I got this error:

GET http://localhost:4000/api/v2/providers/twitter/callback?oauth_token=<xxx>&oauth_verifier=<yyy>

```
{"errors":[{"code":424,"message":"RESTfacility returned error","name":""},{"code":4,"message":"[CreateTwitterIdentity] failed to create user identity","name":""},{"code":1,"message":"[CreateUserIdentity] CreateUserIdentity failed to create identity in store","name":""}]}
```

then the remote appears to be created but never sync.

I don't know if it comes from a bad config or misconfigured docker container

**Comment by sapiens-sapide** [comment]
I was not able to reproduce this issue on a local dev stack.

**Comment by iamdey** [comment]
ok after update rebuild & co
