### ISSUE TITLE
missing contact_id in the user api

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#13]
the route `/me` gives the user and should give the `contact_id` property

**Comment by gdchamal** [comment]
https://gist.github.com/gdchamal/8b82351019a08d54322bf12a5319762a

does it fit ?

**Comment by iamdey** [comment]
yup

**Comment by iamdey** [comment]
useful for https://trello.com/c/suEMQcDU/154-bug-contacts-icons-in-thread-list-does-nt-omit-the-user-comp-0-5

**Comment by gdchamal** [comment]
2 repository impacted, I will prepare MR soon, it's an 'easy' win (except the 2 repositories impact)
