### ISSUE TITLE
A message from myself doesn't display any participant

### ISSUE THREAD

**Issue by gdchamal** [CaliOpen/Caliopen#1307]
I receive a message from myself (an address present on my own contact), the related discussion on the timeline appear with no participant at all

![Opera Instantané_2019-05-06_152730_www caliopen app](https://user-images.githubusercontent.com/341290/57228191-80da7200-7013-11e9-97f7-ebde92aa7d29.png)

**Comment by MonsieurLanza** [comment]
A contact has no name.

**Comment by gdchamal** [comment]
The contact (it's the same for emiter and receiver) have a name
