### ISSUE TITLE
search results w/ "("

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#1405]
BSOD when search term has an opening parenthesis

https://feedback.caliopen.org/t/syntaxerror-unterminated-parenthetical/730

**Comment by MonsieurLanza** [comment]
This is a regexp failing, not JS code. In Highlight component  https://github.com/CaliOpen/Caliopen/blob/836e7ab8945fb72c40284c405d68430ad4dda4d8/src/frontend/web_application/src/scenes/SearchResults/components/Highlights/index.jsx#L41
