### ISSUE TITLE
refactor signin page

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#1422]
* to make it compatible with google oauth requirements 
* and (first things first) to make the purpse of Caliopen understandable to anyone coming directly on this landing page

Specs:
**FIXME**

what do we need ?

* header: 
* sidebar: _what is caliopen / how Caliopen will make you a better person :p …_
* content: signin form + link create account (only the form will change)
* footer: 
  * link to about (https://www.caliopen.org)
  * link to https://www.caliopen.app/privacy-policy.html
  * link to blog
  * link to code source + why it is open source
  * moto (be good)
  * version

**Comment by MonsieurLanza** [comment]
If I may : 
# ~~refactor signin~~ build home page

what do we need ? 
~~header:~~
~~sidebar:~~
~~content:~~
~~footer~~

- signin form + link create account (only the form will change)
- what is caliopen / how Caliopen will make you a better person :p …
- link to about (https://www.caliopen.org)
- link to https://www.caliopen.app/privacy-policy.html
- link to blog
- link to code source + why it is open source
- moto (be good)
- version

The where to put each item is a second time question, to consider only when we know what we have to display.
Google is asking for a home page that explains 
- what is the purpose of the application ?
- who is running it ?

Besides this, if you take a closer look at twitter (or facebook, for instance), you can notice that they both have a home page answering those questions with a login form, and then a *separate* pure login page (which you can reach when you mistype your credentials, for instance).

**Comment by LaurentChemla** [comment]
https://feedback.caliopen.org/t/google-oauth-review-request/765

**Comment by iamdey** [comment]
The purpose of the app:

```
Caliopen est un aggrégateur de correspondance privée (vous recevez tous vos emails et messages privés Twitter au même endroit) qui affiche un niveau de confidentialité associé à tous vos messages.
```
