### ISSUE TITLE
Wrong revoke button highlited

### ISSUE THREAD

**Issue by pguyot** [CaliOpen/Caliopen#1431]
When revoking a device, a full device block is removed from the tree but a revoke button for another device (?) remains highlited.

Experienced on iOS, UA: Mozilla/5.0 (iPhone; CPU iPhone OS 12_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Mobile/15E148 Safari/604.1

**Comment by iamdey** [comment]
it doesn't look highlighted to me (technically speaking, it doesn't have the focus) but the choice of the colors might not be good enough and may be mislead.

In case I'm incorrect, feel free to reopen the issue with more details (eventually screenshots).

Thank you for taking time to make Caliopen better.
