### ISSUE TITLE
List of devices not reloaded

### ISSUE THREAD

**Issue by pguyot** [CaliOpen/Caliopen#1432]
If the list of devices changes (being revoked/verified/created), it is not reloaded, even when navigating in the various tabs (home, address book, conversations). A full web page reload is required to get an updated list of devices.

UA = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15

**Comment by iamdey** [comment]
good catch
