### ISSUE TITLE
let's fight against phishing

### ISSUE THREAD

**Issue by oricou** [CaliOpen/Caliopen#1451]
A friend of mine received a suspicious mail in Gmail. I wanted to check it which means having a look at the source to read the headers and check which server sent the mail. I couldn't find how to do that on Gmail. BTW I don't see how to do that with Caliopen...

Could we have an option to see the source code of a mail?

It could also be nice to check if the From field has the same domain than the server sending the mail (I know they can be different but if you are suspicious and they are different, it helps).

Also it could be helpful to know if TLS has been used (but maybe it is included in the privacy index).

Thanks,

Olivier.

**Comment by sapiens-sapide** [comment]
Thank you @oricou for providing user's feedback. There is a dedicaced place to discuss improvements and features : [feedback.caliopen.org](https://feedback.caliopen.org)
I suggest you to read this [topic](https://feedback.caliopen.org/t/afficher-len-tete-demail-header-et-ou-la-source-raw-message/25)  

Add a like or a comment if it makes sense.
