### ISSUE TITLE
Error HTTP 500 GET https://www.caliopen.app/api/v2/contacts?offset=0&limit=1000

### ISSUE THREAD

**Issue by 87113** [CaliOpen/Caliopen#1589]
Hi, everything in the title. 

I got a recurrent Error HTTP 500 on the url GET https://www.caliopen.app/api/v2/contacts?offset=0&limit=1000 

The message in the body is : elastic: Error 400 (Bad Request): all shards failed [type=search_phase_execution_exception] 

Tested on https://www.caliopen.app/ 0.26

**Comment by iamdey** [comment]
Hello, thank you for the report.
Actually, I did made some maintainance operations on elasticsearch in order
to fix that kind of issue. So I'm surprised this happens to you now,  did
it worked in the previous weeks?

Please send your login to contact at caliopen dot org, I will be able to
see if other users are affected too.
As you may know we're on slowmotion, so I'll do my best to fix that when
I'm back from vacations.

Le mar. 25 avr. 2023 à 15:25, ***@***.*** ***@***.***> a
écrit :

**Comment by 87113** [comment]
Hello, I have the same error today. 
I send my login by email.

**Comment by iamdey** [comment]
Ok found, there are still maintenance operations in progress; your user still not migrated. I'll update this issue when it's done.

**Comment by iamdey** [comment]
Maintenance operations are now done, you should be able to login and see you contacts and messages.

Feel free to reopen the issue if something goes wrong again.
