### ISSUE TITLE
Is this project still maintained ?

### ISSUE THREAD

**Issue by toussa** [CaliOpen/Caliopen#1595]
Hello,

I really like the concept of Caliopen. I discovered its existence few years ago and bookmarked it.
However, it seems that it's not maintained anymore (no more activity since 7months).
Can someone tell us the current status of the project?

Thanks !

**Comment by iamdey** [comment]
Hi @toussa 
thank you for your interest in the project.

For now it's in a (very) slow paced development. 
We still have some ideas but not much time nor enough people involved to do significant progress.

The beta is still running at https://www.caliopen.app new account should be working.

**Comment by toussa** [comment]
Hi @iamdey ,
Thanks a lot for your answer.
Michael
