### ISSUE TITLE
PATCH on devices

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#163]
Unable to perform PATCH request on devices.

How to reproduce:

1. POST a new device on `/api/v1/devices`
2. PATCH on `/api/v1/devices/<id>`

results:

```
{
    "errors": [
        {
            "code": 405,
            "description": "",
            "component": "Device",
            "values": 405,
            "message": "None",
            "property": "HTTPMethodNotAllowed",
            "type": "Method Not Allowed"
        }
    ]
}
```

**Comment by gdchamal** [comment]
not implemented yet, related to https://tree.taiga.io/project/caliopen-caliopen/task/122

**Comment by gdchamal** [comment]
closed by https://github.com/CaliOpen/Caliopen/pull/168
