### ISSUE TITLE
Simplistic routes for messages

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#165]
as discussed in this PR https://github.com/CaliOpen/Caliopen/pull/137#issuecomment-277013429 we need a simplistic routes for "sub" entities like messages: 

`/api/v1/messages/<id_message>` instead of  `/api/v1/discussions/<id_discussion>/messages/<id_messages>`

**Comment by gdchamal** [comment]
I close this issue as it's an user story that will be covered on march sprint
