### ISSUE TITLE
is_primary not set on email creation

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#17]
When I POST this kind of data on `/api/v1/contacts/{id}/emails`:

```
{"contact_id":"a347c94f-e86d-4678-b602-3c8ef0bc7c22","type":"other","address":"foo@bar.tld","is_primary":1}
```

I receive the following:

```
{
  "addresses": {
    "is_primary": 0,
    "date_update" :null,
    "label" :null,
    "address" :"foo@bar.tld",
    "date_insert" :"2016-04-07T13:32:01.425325",
    "type" :"other"
  }
}
```

And then when I load `/api/v1/contacts/{id}/emails` I receive all the emails and is_primary is still 0.

---

Other thing, the schema of the POST response is a bit strange compare to what I've POSTed. May be we should return the same that we expect.

**Comment by gdchamal** [comment]
no more POST on this route, should use PATCH principle even on nested collection like emails, phones. etc
