### ISSUE TITLE
offset params has no effect

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#185]
I want to paginate results on discussions api:

both requests give same result:
* `/api/v1/discussions?offset=0&limit=20`
* `/api/v1/discussions?offset=20&limit=20`

**Comment by gdchamal** [comment]
https://github.com/CaliOpen/Caliopen/blob/master/src/backend/main/py.main/caliopen_main/discussion/store/discussion_index.py#L41

It's a TODO, but don't know yet how to address it correctly in elasticsearch DSL

**Comment by gdchamal** [comment]
fixed with https://github.com/CaliOpen/Caliopen/pull/229
