### ISSUE TITLE
dropdown menu should close on click 

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#205]
When a click happen on item in a dropdown, the dropdown is still opened. 

E.g 

```gherkin
Given I click on user menu
  And I see the menu
 When I click Settings
 Then I should see the setting interface
  And the user menu should be closed
```

**Comment by iamdey** [comment]
I don't know where are you about your new dropdown component @myleneb.

**Comment by myleneb** [comment]
\o/ https://github.com/CaliOpen/Caliopen/pull/517
