### ISSUE TITLE
add polyfill for find()

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#215]
find is not supported by majority of browsers notably for smart devices http://devdocs.io/javascript/global_objects/array/find

babel-polyfill should be added on all build (for now only cordova requires it)

**Comment by ziir** [comment]
I believe this issue to be mis-labeled, to me, it's more about a polyfill and JavaScript cross-browser compatibility strategy.

The `babel-polyfill` way is, IMO, a good one for prototyping without too much hassle, yet it may not suffice for the real world and alternatives exist, each having specific pros and cons.

Perhaps a first draft of the supported browsers and targets would a good start?

**Comment by iamdey** [comment]
the polyfill takes care about:
  * `find`
  * `async/await`
  * eventually `Object.values`
  * ...other eventual es6/7 features

The PR #230 will fix this issue, so I close it now.

@ziir feel free to open a PR if you think about a better solution.
