### ISSUE TITLE
Build of lmtp fail

### ISSUE THREAD

**Issue by gdchamal** [CaliOpen/Caliopen#224]
(.venv) tao~/dev/caliopen/go/src/github.com/CaliOpen/CaliOpen/src/backend/protocols/go.smtp(master|✚3…) % go build github.com/CaliOpen/CaliOpen/src/backend/protocols/go.smtp/cmd/caliopen_lmtpd
# github.com/CaliOpen/CaliOpen/src/backend/protocols/go.smtp/vendor/github.com/CaliOpen/CaliOpen/src/backend/protocols/go.smtp
vendor/github.com/CaliOpen/CaliOpen/src/backend/protocols/go.smtp/receiver.go:28: undefined: guerrilla.BackendResult
vendor/github.com/CaliOpen/CaliOpen/src/backend/protocols/go.smtp/receiver.go:28: undefined: guerrilla.Envelope
vendor/github.com/CaliOpen/CaliOpen/src/backend/protocols/go.smtp/smtp.go:71: undefined: guerrilla.Backend
vendor/github.com/CaliOpen/CaliOpen/src/backend/protocols/go.smtp/smtp.go:72: undefined: guerrilla.Backend
vendor/github.com/CaliOpen/CaliOpen/src/backend/protocols/go.smtp/smtp.go:81: unknown field 'AllowedHosts' in struct literal of type guerrilla.ServerConfig
vendor/github.com/CaliOpen/CaliOpen/src/backend/protocols/go.smtp/smtp.go:93: not enough arguments in call to guerrilla.New
	have (*guerrilla.AppConfig, <T>)
	want (*guerrilla.AppConfig, "github.com/CaliOpen/CaliOpen/src/backend/protocols/go.smtp/vendor/github.com/flashmob/go-guerrilla/backends".Backend, log.Logger)
vendor/github.com/CaliOpen/CaliOpen/src/backend/protocols/go.smtp/smtp.go:93: multiple-value guerrilla.New() in single-value context

using govendor sync and a clean GOPATH

**Comment by sapiens-sapide** [comment]
Sorry, but the revision number for guerrilla dependency is incorrect in vendor.json. I'll fix it.

**Comment by gdchamal** [comment]
fixed
