### ISSUE TITLE
Build of docker api image does not work

### ISSUE THREAD

**Issue by gdchamal** [CaliOpen/Caliopen#231]
Somehow a dependency problem with vendor.

Doing a govendor update +vendor make it work (but it's not a correct solution)

https://pastebin.com/bBSbsr21

**Comment by gdchamal** [comment]
Doing a govendor update +vendor and then build work

fixed with:
https://github.com/CaliOpen/Caliopen/commit/9237b58d6e1185438f7f9ed8a3718aaf32ce4e0b

**Comment by iamdey** [comment]
\o/
