### ISSUE TITLE
config for CLI

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#243]
unable to change the hostname for the broker. so the import emails command might not work within docker:

https://github.com/CaliOpen/Caliopen/blob/master/src/backend/tools/py.CLI/caliopen_cli/commands/import_email.py#L84

also the link between cli and broker is missing

**Comment by gdchamal** [comment]
I'm not confident with broker/nats/message_handler need to import email from CLI.

And we can't express link so easily as depending on CLI task the storage layer is differently setup and the broker consider need of a caliopen keyspace to run (so can't run until setup cli task is done)

I think we will get back to a simpler injection method as it was done before, we have to discuss with @sapiens-sapide about the parsing stuff again to fix it.

**Comment by iamdey** [comment]
oh. I didn't saw your comment before trying to patch.

**Comment by gdchamal** [comment]
As discussed we move full parsing logic of a raw message in message_handler, then CLI will insert raw message as done by broker and will process it synchronously using same code as message_handler for delivery processing.

CLI will not need anymore broker and nats to run for import of messages

**Comment by sapiens-sapide** [comment]
So sad…

**Comment by iamdey** [comment]
I'm agree with @gdchamal, 

broker is meant for email (if I understand right); 
Caliopen is not email; 
it sounds obvious for me that the business logic happens in a kind of middleware (message_handler) and is not duplicated (DRY, Single Responsibility, Separation of Concerns)

(I really need to go deep into SOLID https://en.wikipedia.org/wiki/SOLID_%28object-oriented_design%29)

**Comment by sapiens-sapide** [comment]
« Caliopen is not email ». That is exactly why the role of the broker is to marshal an email into a Caliopen's Message object.  
Thus, Caliopen can handle a Message object (of type email), as it will do with other message types.  
The business logic of enhancing message properties with references, discussion belonging, PI, etc. has always been done within "main", never into the broker.   
Brokers are components in charge of marshal/unmarshal to/from our message object model and external message models.

**Comment by gdchamal** [comment]
CLI is not an MUA, this is a simple tool for development purposes and must stay simple.

Bring the whole stack up to create a message into caliopen (whatever protocol it is) is not a correct solution and we must find a simpler solution.

And broker deliver an envelope to an user and don't have to know about the content (except for user delivery routing at least). That's the reason I want the parsing logic in main and not in broker.
