### ISSUE TITLE
[Front] Interface bug within a discussion list : avatar not well positionned

### ISSUE THREAD

**Issue by sapiens-sapide** [CaliOpen/Caliopen#284]
<img width="1027" alt="capture d ecran 2017-05-03 a 10 31 41" src="https://cloud.githubusercontent.com/assets/1287627/25653215/3d131202-2fec-11e7-87ec-37f47c2884c1.png">

**Comment by iamdey** [comment]
can't reproduce. (I've seen this mail when enabling html rendering)
