### ISSUE TITLE
UX: liste des participants

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#285]
En discutant aec @sapiens-sapide on se rend compte que la présentation des participants à une discussion n'est pas très pratique, surtout pour se rendre compte soit même de l'impact sur le PI (à l'usage je sais quels contacts vont plomber le PI de mes messages).

Pour référence : https://projects.invisionapp.com/d/main#/console/9521379/213688220/preview

On pensait à : 

* onglet: afficher `excerpt`, càd le résumé du dernier message ce qui est raccord avec ce qui est affiché dans la liste des discussions
* entête de discussion: liste des participants
* Reply: reprendre la liste des participants, leurs PI et les interactions possibles

**Comment by Lauth0** [comment]
@iamdey J'ai rien compris, désolé :/
Faudrait qu'on en discute de vive voix, que vous m'expliquiez votre problème...
