### ISSUE TITLE
[messages list] Add the name of the contacts to identify the conversation

### ISSUE THREAD

**Issue by Lauth0** [CaliOpen/Caliopen#3]
Add the name of the contacts to the right of the avatar:

![name of the contacts](https://cloud.githubusercontent.com/assets/6246015/13946923/e962da9e-f017-11e5-9903-77c8d2ae77bc.png)

In case of multiple contacts discussion, display some names (number to define) and add a counter at the end of the line:

![multiple contacts discussion](https://cloud.githubusercontent.com/assets/6246015/13946988/432eb4da-f018-11e5-9c5e-f8e08fbf4776.png)

**Comment by iamdey** [comment]
yes and in tabs too

**Comment by iamdey** [comment]
fixed
