### ISSUE TITLE
incorrect participants list in discussion object returned by backend

### ISSUE THREAD

**Issue by sapiens-sapide** [CaliOpen/Caliopen#309]
The `discussion` object returned by backend on route /api/v1/discussions/{discussion_id} does not have an accurate list of all participants within the discussion.  

Consequently, it is currently not possible to save/send replies from frontend in some discussion because the backend replies with a `422 Patch Error`.  

[Problem is that our `UserMessageQualifier` currently puts in the same discussion, messages that have different participants…]

**Comment by gdchamal** [comment]
the specification about how to manage discussions with many participants is not yet achieved. So this is a naive and default implementation, and totally wrong I know.

I can't consider it as a bug, I close this issue
