### ISSUE TITLE
contact book - duplicated alphabetic group 

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#341]
Don't know if it is due to back or front or inconsistent data (cf. 2nd screenshot)

![capture d ecran de 2017-06-14 11-33-08](https://user-images.githubusercontent.com/65737/27125727-852bd27a-50f5-11e7-84f1-a6b9cfd497e4.png)

![capture d ecran de 2017-06-14 11-32-58](https://user-images.githubusercontent.com/65737/27125726-839b79ce-50f5-11e7-80e7-913eb422a0b5.png)

**Comment by myleneb** [comment]
yes: as `contact.title` is null for this entry, the function that sorts contacts by first letters bugs (I didn't found how to fix it on frontend).
This shouldn't happen because `contact.title` will never, never be null, according to @gdchamal

**Comment by iamdey** [comment]
but happened :D

**Comment by gdchamal** [comment]
In fact there is only one contat with title null due to malformed fixture.
I'll fix import function to not create contact if title is null

**Comment by iamdey** [comment]
I think the actual contact with bad fixture is the user

**Comment by iamdey** [comment]
title is now always given. bug doesn't appear anymore
