### ISSUE TITLE
incorrect default access rights on .data directory in start script

### ISSUE THREAD

**Issue by sapiens-sapide** [CaliOpen/Caliopen#37]
[`start`](https://github.com/CaliOpen/caliopen-dev/blob/master/start) script in caliopen-dev creates `.data` directory with the default host's umask. If umask is set to 022 or greater, the `.data` directory will be unwritable => cassandra container will not run.
The script should explicitly set write access for user to the `.data` directory.

**Comment by gdchamal** [comment]
no more valid issue as we move out from docker for storage engines
