### ISSUE TITLE
message duplicated

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#388]
steps to reproduce:

1. write a new message without recipient
2. send (it fails)
3. add recipient
4. send

message is duplicated, one has missing author

(don't know if it is front or back)

**Comment by sapiens-sapide** [comment]
How a message could be duplicated ? If you call `GET …/messages/{message_id}` you could only have one message at a time.   
In your case, if I make a request on `…/messages?discussion_id={discussion_id}` after step 4, I get only one message again…

BTW, when testing your case, I fixed an issue related to participant's creation (commit #3d2c676).  
**NB: route has changed from V1 to V2 !**

**Comment by iamdey** [comment]
My though is the client doesn't handle the error correctly:

Save is ok but send fails so the client think the draft is still new (and duplicate it the next time)

**Comment by iamdey** [comment]
may be related https://feedback.caliopen.org/t/mauvais-message-a-l-arrivee/324/2

**Comment by iamdey** [comment]
errors are now correctly handled, so it should be ok
