### ISSUE TITLE
[messages list] Show only the number of messages and not « x/x »

### ISSUE THREAD

**Issue by Lauth0** [CaliOpen/Caliopen#4]
Show only the number of messages:

![number of messages](https://cloud.githubusercontent.com/assets/6246015/13947102/cb5d4db2-f018-11e5-8c4c-926a60560bbd.png)

and not « x/… »

![number of messages-2](https://cloud.githubusercontent.com/assets/6246015/13947106/cf772d0a-f018-11e5-853a-d3284dd70c92.png)

**Comment by iamdey** [comment]
don't you think it is usefull to know the number of unread message / read ?
