### ISSUE TITLE
[API] delete message config

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#420]
deleting a message almost works great on the frontend cf. #418 

but it is not yet smooth enough:

* after a message deletion the GET on `/api/v2/messages?offset=0&limit=20&discussion_id=<id>` is not synchronized (status 304), the message is still present so the client doesn't react as expected.

**Comment by sapiens-sapide** [comment]
Fix by commit #5199dd4

**Comment by iamdey** [comment]
looks good
