### ISSUE TITLE
specify caliopen team member add/remove process

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#426]

**Comment by myleneb** [comment]
### Add/Remove Team members on public website

#### member adds pic and tagline on taïga:
- https://tree.taiga.io/project/caliopen-caliopen/task/171

#### update wp pages "Meet the team" for each language
- update post=519 (fr)
- update post=541 (en)
- update post=1201 (it)

**Comment by iamdey** [comment]
https://pad.caliopen.org/p/gestion_team
