### ISSUE TITLE
dropdowns look ugly in safari/mac on contacts tab

### ISSUE THREAD

**Issue by sapiens-sapide** [CaliOpen/Caliopen#440]
![capture d ecran 2017-08-24 a 12 13 59](https://user-images.githubusercontent.com/1287627/29661961-f5f1cd72-88c5-11e7-93d6-9bd11fdd48ed.png)

**Comment by myleneb** [comment]
This is because we don't use any vendor trick in css.
Something can be done with some little hack like in: https://codepen.io/fabiomcosta/pen/Ilzpa 
what do you think of it @iamdey ?

**Comment by myleneb** [comment]
@dey 
I pushed a fix here: https://github.com/CaliOpen/Caliopen/compare/fix/frontend/SelectFieldGroup can you have a look and tell what you think? It works fine for chrome, firefox and webkit browser Epiphany (suppose it works too for opera) :)

**Comment by iamdey** [comment]
it seems the good news is Caliopen is working on safari
