### ISSUE TITLE
Patch contact.identities w/ incoherent data

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#447]
I was able to patch a contact w/ this payload (status 204):

```
{
	"current_state": {},
	"identities": [{
		"name": "@foobar"
	}]
}
```

The key `type: 'twitter'` is missing, it should not be possible.

(Afterward I got err 500 on GET contacts, GET contact is 304 so PATCH contact is 409)

**Comment by sapiens-sapide** [comment]
1. `type` is not required for now within `SoccialIdentity` object. Thus, it is normal that API accepts identity without the `type` attribute.
2. On branch `master`@022c5ab I was able to patch a contact with the above payload. I got a `200 OK` ; I could retrieve the patched contact with the new identity correctly added…

**Comment by iamdey** [comment]
sounds ok but other properties has the same issue #466
