### ISSUE TITLE
autocomplete does not add email address to participants

### ISSUE THREAD

**Issue by sapiens-sapide** [CaliOpen/Caliopen#452]
Context : compose a draft in frontend.
Bug description : 
when selecting a contact from the suggest dropdown list, the contact is added to participants list without its email address. Therefore, API refuses to save or send the draft.

**Comment by iamdey** [comment]
result

```
[{"contact_id":"31ca33dd-2620-4c85-91e5-67f79683f76a","label":"acm","source":"contact"},{}]
```

As discussed: a participant must has an address.  (should be the preferred one or he first).

In functional terms: if a participant is a known contact, after being added, the user will be able to change its address (by clicking on a dropdown, not yet implemented in my memory).

**Comment by iamdey** [comment]
this issue is covered by this US : https://tree.taiga.io/project/caliopen-caliopen/us/326?milestone=149713
