### ISSUE TITLE
Message's plain body not correctly rendered.

### ISSUE THREAD

**Issue by sapiens-sapide** [CaliOpen/Caliopen#455]
Plain text bodies are rendered without `<pre>` tags, thus linefeeds are not rendered. 
[as discussed with @iamdey and @gdchamal, backend will return a new field : `body_is_plain` of type boolean to help frontend to correctly render the body].

**Comment by sapiens-sapide** [comment]
backend feature proposed by PR #456

**Comment by myleneb** [comment]
close with https://github.com/CaliOpen/Caliopen/pull/468
