### ISSUE TITLE
DiscussionItemActionsContainer UI on mobile view

### ISSUE THREAD

**Issue by myleneb** [CaliOpen/Caliopen#464]
on mobile view, `DiscussionItemActionsContainer` is hiding `DiscussionItem`

![](https://camo.githubusercontent.com/2d6a4bb26bc1df93c64d7090263ef0d688afd6cd/68747470733a2f2f6672616d617069632e6f72672f6e704d6e636e6644777156552f7773354131575563714444532e6a7067)

as discussed with @Lauth0 it should swipe.
What do you think @iamdey ?
poke @judbd

**Comment by iamdey** [comment]
the swipe can be done using the library already in the project https://www.npmjs.com/package/react-tappable

**Comment by myleneb** [comment]
close with https://github.com/CaliOpen/Caliopen/pull/492
