### ISSUE TITLE
set_read message

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#481]
When rendering a discussion, all messages will be passed as read, it is not consistent with the algo of message display mode https://tree.taiga.io/project/caliopen-caliopen/task/439?kanban-status=815892

We have to test different way to change the state of a message.

First step is to pass set_read when a message is at least displayed in the webview.  
Second step is to delay the set_read action according to read speed of the user.

**Comment by myleneb** [comment]
I try something on this branch: https://github.com/CaliOpen/Caliopen/tree/fix/frontend/set-message-read with lib [react-visibility-sensor](https://github.com/joshwnj/react-visibility-sensor)
When `<Message>` is displayed in window viewport. it call function to make message.is_unread false.
For testing purposes, I also added a checkbox in `<Message>` to toggle read/unread attribute.

**Comment by iamdey** [comment]
looks good to me,

**Comment by iamdey** [comment]
as discussed this morning, we some choices to do:

* mark message as read -> automatically when message appear in viewport after a few seconds
* mark one message as unread:
  * from timeline (from swipe/hover menu)
  * from message item in a discussion (from ellipsis menu) but the tab must be closed else it will be automatically set read (or scroll up to previous message if any but it might not works well)
* ¿mark all messages from discussion as unread? -> from general menu bar (same discussion tab should be closed afterward)

Do you see other options ?
