### ISSUE TITLE
/api/v2/messages total is incorrect

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#490]
The total in response of GET `/api/v2/messages?offset=0&limit=20`

should be the total amount of messages for this query without being affected by offset/limit

for now it max 20 which is wrong.

PS:
I didn't check GET `/api/v2/messages?offset=0&limit=20&discussion_id=<id>`
But same remark, the total should be affected only by discussion_id parameter.

**Comment by gdchamal** [comment]
weird, the total is given by elasticsearch query and should not be different depending pagination parameters, as far as I understand how it's work

**Comment by iamdey** [comment]
I confirm If I set limit 10 I get total: 10 and when limit 20, total: 20 with or without discussion_id param

**Comment by sapiens-sapide** [comment]
weird++, it should have been fix by commit #b714198 « Fix erroneous 'total count' returned by index's FilterMessages func ».

**Comment by iamdey** [comment]
I'll rebuild my stack and tell if it is fixed

**Comment by iamdey** [comment]
fixed
