### ISSUE TITLE
Save scroll position by tab

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#521]
In order to prevent strange navigation between tabs, the position of the page must be saved.

This is will be saved in redux store, on refresh it will be lost, that's not a problem.

The y axis value cannot be used: on window resizing or toggling portait/landscape display mode or refreshing data, this value will not make sense anymore.

**So an anchor can be used to declare where the scroll must be placed.**
The anchor can be a message id or a contact id or a section in settings form or contact page.

other idea;

**the anchor id can be simply saved in tab url** So we only have to read the hash of the anchor.
But it requires to update the current tab (using a **debounce** to prevent blinking in browser url).

This task is related to **reply-to** which auto-scroll to textarea
and click on a message in timeline auto-scroll to message cf. #424

**Comment by iamdey** [comment]
WIP #667

**Comment by VincentJ-Caliopen** [comment]
Namely, scroll should be independent between tabs.
Currenly if I scroll in my _messages_ tab it also scrolls my _contact_ tab for exemple.

**Comment by VincentJ-Caliopen** [comment]
When I open a discussion by clicking a message in the timeline, the tab should open scrolled to the target message.

**Comment by iamdey** [comment]
done
