### ISSUE TITLE
err js while selecting participant

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#563]
`Uncaught (in promise) TypeError: Cannot read property 'filter' of null`

```
      , d = function(e) {
        return e.filter(function(e) {
            return "contact" === e.source
        })
```

_not blocking_

---

It is due to an unexpected response from api:

```
req : GET https://alpha.caliopen.org/api/v2/participants/suggest?q=foo@&context=msg_compose
resp:

null
```

it should respond an empty array 

```
[]
```

ok with at least one suggestion

**Comment by sapiens-sapide** [comment]
fix by commit #d057085
