### ISSUE TITLE
incorrect counting of objects returned on route `/contacts`, `/threads`

### ISSUE THREAD

**Issue by sapiens-sapide** [CaliOpen/Caliopen#57]
The json returned on route `/contacts` has a field `"total"` that should return the total number of contacts found for the user and the given PI range.
Currently, the `"total"` field is fill with the number of contacts returned on the page, as set by the `limit` parameter of the query. 
For example : if a query on `/contacts` found 50 contacts in db, the `"total"` field in the returned json should be set to 50, no matter the `limit` paramater and the effective number of contacts returned. 

Same issue on route `/threads` for returned threads. 
Same issue on route `/treads/{thread_id}/messages`.

**Comment by iamdey** [comment]
related to #32

**Comment by sapiens-sapide** [comment]
fix by PR #67
