### ISSUE TITLE
popin realm authentication

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#580]
![capture du 2017-10-30 08-51-46](https://user-images.githubusercontent.com/65737/32160061-61c05d52-bd50-11e7-8409-67f77d1d6432.png)

Due to how api v2 handle bearer, when user loose authentication, this popin appears.

Express server is just a basic proxy: it decodes the cookie and send the bearer to backend, the cookie is valid until the session exists (until browser is closed).

Client cannot handle this directly. The xhr request is pending and the browser asks the user before javascript can do anything (am I right ?)

**Comment by sapiens-sapide** [comment]
Fix by commit #39f2162.
