### ISSUE TITLE
frontend makes invalid request on route …/messages/…/actions

### ISSUE THREAD

**Issue by sapiens-sapide** [CaliOpen/Caliopen#582]
api2 service logs a lot of call to these invalid urls : `/api/v2/messages/undefined/actions` with a valid payload of kind `{"actions":["send"]}`.

As you can see, message_id is missing, we have `undefined` instead of a valid uuid string.

**Comment by iamdey** [comment]
> 15:46 stansab je suis dan ff
> 15:46 chamal en train de finaliser, c'est bientot pret pour ouvrir plus ;)
> 15:46 stansab je compose un draft
> 15:47 stansab je met un simple espace dans le body
> 15:47 stansab je save
> 15:47 stansab je mets un email
> 15:47 stansab tab pour valider le email
> 15:47 stansab puis « envoyer »
