### ISSUE TITLE
delete a discussion does not delete the draft

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#585]
https://feedback.caliopen.org/t/bouton-supprimer-inactif-dans-un-brouillon/272

**Comment by sapiens-sapide** [comment]
btw, deleting a draft doesn't work. Hit « Supprimer » button on top of draft window does nothing (not even a `POST` on api)

**Comment by iamdey** [comment]
may be it's a feature to not delete a draft on hitting this button, what do you think @Lauth0  ?

So we just need to disable the delete button.

**Comment by iamdey** [comment]
as we discussed earlier we need a button w/ confirmation step

**Comment by iamdey** [comment]
TODO:

* [ ] modal confirm
* [ ] confirm delete messages
* [ ] confirm delete contact
* [ ] confirm delete draft when delete a discussion
