### ISSUE TITLE
disable send button on send & notify

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#594]
the user has no idea if a message is sent.

We need to disable the send button after one click to prevent double click

And in order to notify the user we 3 solutions : 
* Add a spinner in the send button
* display a success notification
* Both previous solutions

Since we will add a "in progress" state in message https://tree.taiga.io/project/caliopen-caliopen/us/487?no-milestone=1, I think the spinner is enough. What do you think @Lauth0

**Comment by iamdey** [comment]
cf. https://feedback.caliopen.org/t/notification-d-envoi-de-mail/50

**Comment by sapiens-sapide** [comment]
Is it possible to also disable the send button as long as there is no recipients ?  

FYI, we see a lot of requests to send draft without recipient in alpha logs. APIs handles it correctly but it creates unecessary calls.

**Comment by iamdey** [comment]
yes, @myleneb did it, it's merged in develop

**Comment by sapiens-sapide** [comment]
👍
