### ISSUE TITLE
Create a page title by URL

### ISSUE THREAD

**Issue by judbd** [CaliOpen/Caliopen#597]
Create a unique page <title> for each page or at least for each section.

**Comment by iamdey** [comment]
can you be more specific about a "`<title>` for each section" ?

**Comment by judbd** [comment]
Examples:

- **Discussion page:** Discussions 0 / 23 (unread/read count) - username@alpha.caliopen.org - Caliopen, be good!
- **Tab:** Name of tab / recipients - username@alpha.caliopen.org - Caliopen, be good!
- **Received message:** date, time, from - username@alpha.caliopen.org - Caliopen, be good!
- **Message sent:** date, from, recipients - username@alpha.caliopen.org - Caliopen, be good!

**Comment by myleneb** [comment]
fixed by https://github.com/CaliOpen/Caliopen/pull/675
