### ISSUE TITLE
Comprehensive wording at signup (alpha)

### ISSUE THREAD

**Issue by judbd** [CaliOpen/Caliopen#609]
`[nom d'utilisateur]` sera utilisé pour créer votre adresse mail **utilisateur**@alpha.caliopen.org (ou encore mieux, donner un exemple dynamique sous le champ qui reprend le contenu du form)
`[mot de passe]`
`[email d'invitation] ` merci de renseigner l'email que vous avez fourni lors de la demande d'invitation.
* Supprimer la coche des CGU tant qu'on a pas de CGU
* Élargir le bloc pour que ce soit plus simple à lire

**Comment by myleneb** [comment]
fix: https://github.com/CaliOpen/Caliopen/pull/629
