### ISSUE TITLE
Login doesn't work if i registred the credentials in my browser

### ISSUE THREAD

**Issue by AlxxxlA** [CaliOpen/Caliopen#611]
Hi,

I've registred the credentials for https://alpha.caliopen.org/ on my browser. If I disconnect then try to reconnect with the login and password autofilled, an error is diplayed 

![selection_046](https://user-images.githubusercontent.com/5237496/32370186-5dfd58ca-c08c-11e7-8e05-e90c61f7710d.png)

To reproduce : 
- Login on Caliopen and save the credentials in the browser
- Disconnect from Caliopen
- Try to reconnect with the credentials autofill by the browser

I'm using Firefox ESR 52.4.0

**Comment by AlxxxlA** [comment]
Already reported on feedback : https://feedback.caliopen.org/t/reconnexion-impossible/123/2

Relative to : https://github.com/facebook/react/issues/1159

**Comment by iamdey** [comment]
it's ok to keep it open until we have a fix

**Comment by myleneb** [comment]
@iamdey  I tried to fix it here: https://github.com/CaliOpen/Caliopen/pull/697
based on this tip: https://medium.com/@dschmidt1992/auto-fill-with-redux-forms-9b51ad8ef962

**Comment by myleneb** [comment]
Fixed with https://github.com/CaliOpen/Caliopen/pull/697
