### ISSUE TITLE
[feature] support multiple sessions

### ISSUE THREAD

**Issue by jibe-b** [CaliOpen/Caliopen#612]
When opening both a session in a browser (Firefox 56) and in rambox (https://rambox.pro, based on Chromium framework)

both second session opens but in a few seconds an alert notification appears "no longer authenticated"

Wish: support multiple parallel sessions.

**Comment by gdchamal** [comment]
We will support correctly multiple session when 'Device' will be managed correctly. As design of this part is not complete we remove it from alpha scope.

For alpha purpose I'll try to make it possible to get multiple connections differently

**Comment by gdchamal** [comment]
We will start working on devices v0 integration. It will permit to have concurrent session on different declared devices.
