### ISSUE TITLE
[bug] basic authentication handled by browser fail

### ISSUE THREAD

**Issue by jibe-b** [CaliOpen/Caliopen#613]
After a deauthentication done by the server (due to 2 parallel sessions, see #612 ),

browser (Firefox 56) opens window to enter login and password to authenticate,

but after credentials are entered, the authentication window appears again and again.

**Comment by jibe-b** [comment]
Absolutely

**Comment by AlxxxlA** [comment]
Hi,

Seems to be duplicate with this ticket : https://github.com/CaliOpen/Caliopen/issues/580
Is this the same issue ?
