### ISSUE TITLE
describe how to fill the phone field 

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#620]
the phone format is very strict (requires the `+<region>`).

We need to add an explanation on how to fill

**Comment by gdchamal** [comment]
Error is 

```
{"errors": [{"code": 422, "description": "PATCH payload was malformed or unprocessable", "component": "contact", "values": 422, "message": "unable to unmarshall patch into object <{\"phones\": {\"0\": {\"number\": [\"Missing or invalid default region.\"]}}}>", "property": "MergePatchError", "type": "Patch Unprocessable"}]}
```

Use of https://github.com/catamphetamine/react-phone-number-input should make it simpler to have the correct expected syntax for phone number

**Comment by gdchamal** [comment]
will relax normalization backend side:

https://github.com/CaliOpen/Caliopen/pull/650

**Comment by iamdey** [comment]
I reopen for the react-phone-number-implementation

**Comment by iamdey** [comment]
we can save whatever we want, since phone number is unused by caliopen yet, it is unecessary to keep it open
