### ISSUE TITLE
Storing attachment of inbound message fail with SMTP 554 error

### ISSUE THREAD

**Issue by gdchamal** [CaliOpen/Caliopen#637]
https://feedback.caliopen.org/t/discussion-incomplete/263/4

**Comment by gdchamal** [comment]
It's not related to attachment but rather than an incomplete SPF, reverse DNS configuration.

No 554 error seen since 8 November, last log:

```
Nov  8 17:17:08 localhost postfix/smtp[29269]: ED84740040: host mx00.gmx.net[212.227.15.10] refused to talk to me: 554-gmx.net (mxgmx012) Nemesis ESMTP Service not available 554-No SMTP service 554-Bad DNS PTR resource record
```

**Comment by sapiens-sapide** [comment]
Probably a misconfiguration :  error comes from minio not finding the right bucket to store attachment file.
