### ISSUE TITLE
search results display em tag

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#639]
afaik, it's due to how elastic search render highlights.

```
"highlights": {
	"body_plain": ["> From: Lars Magne Ingebrigtsen <larsi@gnus.org>\n> Date: Mon, 28 Mar 2016 20:19:13 +0200\n> Cc: <em>dev</em>"],
	"participants.label": ["<em>dev</em>@caliopen.local"]
}
```

**Comment by sapiens-sapide** [comment]
@iamdey : how highlights should be rendered for frontend ? No tag at all ? frontend will add it ? I don't think it is a good idea…

**Comment by iamdey** [comment]
I think message is almost the same as in Timeline except we display the excerpts, a simple string) where we found the terms:

`...{excerpt1 containing <b>term(s)</b>} ... {excerpt2 containing <b>term(s)</b>} ... etc.`

for contact it's a bit different, it is almost the same as in ContactBook except we should give the property where we found the terms:

```
{name eventually with <b>term(s)</b>}
[email/twitter/address]: ...{excerpt containing <b>term(s)</b>}
```
can you be more specific on why it is not a good idea to parse highlights client side ?

Now it is a simple `<b/>` but we might need to set a specific className.

**Comment by sapiens-sapide** [comment]
ok, we could strip highlights tags put by ES.  
But be aware that, as far as I understand ES, it could returned documents and highlights that are not equals to the terms of the search, if ES scored those related terms as «relevant».  Consequently, frontend will not be able to highlight this terms…

**Comment by iamdey** [comment]
may be the best way is to configure ES to use our own marker if it is possible.

**Comment by sapiens-sapide** [comment]
which markers would you like ?

**Comment by iamdey** [comment]
I don't know what are the best practices. After thinking about a bit, we can keep the em tags and parse those client side.

**Comment by myleneb** [comment]
Fixed with https://github.com/CaliOpen/Caliopen/pull/677
