### ISSUE TITLE
Reset password will not work if a recovery email is set for multiple account.

### ISSUE THREAD

**Issue by sapiens-sapide** [CaliOpen/Caliopen#673]
Current backend implementation of the reset password procedure will not handle the case where the recovery email entered in the form leads to find more than one user.

**Comment by gdchamal** [comment]
In fact only one recovery email can exist at a time. As we have a recovery_email table that can contain uniaue recovery email.

We must restrict to an unique recovery_email or remove logic around lookup up for such value and capability to reset password with such value.

**Comment by sapiens-sapide** [comment]
Must discuss it ! 
* Option 1 : unique recovery_email, meaning that one can not create multiple accounts with the same recovery_email
* Option 2 : allow to reuse the same recovery_email for different accounts : means that the reset password process could only be triggered with username : ie user who wants to reset password MUST remember its username.

**Comment by LaurentChemla** [comment]
option 1

**Comment by iamdey** [comment]
option 1 (comme le chef a dit)

but I don't think it's the best solution ... but still better than the option 2

**Comment by sapiens-sapide** [comment]
Option 1 enforced by PR #683
