### ISSUE TITLE
popup for participants suggestion not well formatted

### ISSUE THREAD

**Issue by sapiens-sapide** [CaliOpen/Caliopen#674]
In the case where both contacts AND participants have been found, the popup may displays one participant's email address at the same level than another contact's email address. This is confusing, because the user may believe that the participant email belongs to the contact above. 
Here is a screenshot to understand : 
![capture d ecran 2017-11-24 a 14 17 25](https://user-images.githubusercontent.com/1287627/33212620-54b0d3de-d124-11e7-9d56-16eeea1f34e7.png)
In this popup, email addresse `stan@mailde…` has been found from participants' emails, but it looks like it is a secondary email for contact `caisse`, which is not the case.

**Comment by myleneb** [comment]
Fixed with https://github.com/CaliOpen/Caliopen/pull/678
