### ISSUE TITLE
filter message sent/received/all in Timeline

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#684]
https://feedback.caliopen.org/t/gestion-de-laffichage-des-discussions/94/44?u=dey

Add a dropdown select with the 4 options

- received (default)
- all
- draft
- sent

notice the limit/offset applied to all messages unfiltered, may be the filter has to be also applied to the api

**Comment by sapiens-sapide** [comment]
* Easy to filter by draft… Actually, it does work right now out of the box ! (just add is_draft=true in the query params)
* Not so easy to filter by received/sent because it is not a core property of Message objects. I need to find a solution.

**Comment by sapiens-sapide** [comment]
For now, it is difficult for us to __efficiently__ retrieve messages that have been _sent_ or _received_. If we need this kind of filtering, I suggest we add two properties to messages (following the jmap specifications) : 
* sentAt: Date
* receivedAt: Date

**Comment by iamdey** [comment]
an other advantage is to have a self explanatory property for message sorting cf. #679
