### ISSUE TITLE
call-to-action prevent clic on sub elements

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#703]
https://feedback.caliopen.org/t/probleme-de-chevauchement-du-call-to-action-avec-dautres-elements-de-linterface/99/3

The first question is what is the futur of call-to-action ?

**Comment by myleneb** [comment]
overlay fixed by https://github.com/CaliOpen/Caliopen/pull/784
@iamdey do you want to keep the issue open to talk about the futur of call-to-action?

**Comment by iamdey** [comment]
it seems the call-to-action aka floating action buttons will be kept. So if it fixed as well -> close :)
