### ISSUE TITLE
Informations stripped in mailer daemon email

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#709]
https://feedback.caliopen.org/t/mailer-deamon-nindique-pas-ladresse-incorrect/361

**Comment by sapiens-sapide** [comment]
Could we have more feedback of the incorrect error returned ? Under what circumstances?

**Comment by iamdey** [comment]
Message sent:

![capture d ecran de 2017-12-13 10-50-12](https://user-images.githubusercontent.com/65737/33932554-81de52ae-dff3-11e7-9150-884ab6ad74e1.png)

Mailer daemon response
![capture d ecran de 2017-12-13 10-50-40](https://user-images.githubusercontent.com/65737/33932557-83e323ea-dff3-11e7-9d52-6053d59a336a.png)

**Comment by sapiens-sapide** [comment]
Probably a problem with the body sanitizer, because the message returned is the standard mail returned by postfix. I'll have a look at the raw message in db to confirm.

**Comment by iamdey** [comment]
fixed
