### ISSUE TITLE
ContactBook optimizations

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#727]
provide an optimized API for the  contact book with less properties

* title
* tags

**Comment by Motokiyo** [comment]
And also not so much latency when we go on the page. Each time, the contact page begin empty and need maybe ten or fifteen seconds to appear. I put in 500 contacts.

**Comment by sapiens-sapide** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Contacts API v1-> v2](https://trello.com/c/1QyzvyAn/8-contacts-api-v1-v2)

**Comment by sapiens-sapide** [comment]
@iamdey : only `title` and `tags` ?? May be also : 
* avatar (url to avatar)
* contact_id
* family_name & given_name (for sorting purpose) ?
* tags

**Comment by iamdey** [comment]
only `title` but this issue will be blocking https://github.com/CaliOpen/Caliopen/issues/614

I'll fix this asap

**Comment by iamdey** [comment]
* avatar (url to avatar)
* contact_id
* title
* tags

**Comment by gdchamal** [comment]
it will not fix latency to give back less information on a dedicated API.

We musn't not load all contacts from backend to display a contact book with alphabetic letters to display, that's not a good practice.

A load more or other pagination mechanism should be available on client for huge address book.

To find a contact, search function is here for that, or user will have to paginate all it's contacts, that will be loaded page per page from backend.

**Comment by gdchamal** [comment]
contact api in v2 will arrive in a near release (not the next one).

It will benefit many improvements and will be a better base to start optimization
