### ISSUE TITLE
Make Date property within draft to be updated each time draft is edited

### ISSUE THREAD

**Issue by sapiens-sapide** [CaliOpen/Caliopen#736]
For now, Date property within draft is not set until draft is sent. We propose to set/update the Date property each time the draft is updated by user, and, finaly, to set it to date sent when the message will be sent.

**Comment by iamdey** [comment]
IMO, "never trust user's input"

**Comment by iamdey** [comment]
I think this is related, the answer date is before the original:

![screenshot-2018-4-6 dey bruit-contraire net dey alpha caliopen org - dey alpha caliopen org - caliopen be good 2](https://user-images.githubusercontent.com/65737/38409675-93442f6c-3982-11e8-871d-a2c2eba65b8e.png)

**Comment by sapiens-sapide** [comment]
PR #895 changed the way draft'date is computed.
