### ISSUE TITLE
POST a tag with a label with upercases is always lowercased

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#745]
POST /api/v2/tags

```
{"name":"loiso","label":"Loiso"}
```

GET  /api/v2/tags
```
{
  total: 1,
  tags: [
    {"name":"loiso"
    ,"date_insert":"2018-01-03T14:46:32.656Z","importance_level":0
    ,"label":"loiso"
    ,"type":"user"
  }]
}
```

**Comment by sapiens-sapide** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix tag label issue](https://trello.com/c/uMCWf8vg/12-fix-tag-label-issue)

**Comment by iamdey** [comment]
Also when trying to patch the label (same characters, different cases) it fails:

```
{"current_state":{"label":"yolo"},"label":"Yolo"}
```
```
{"errors":[{"code":422,"message":"[RESTfacility] tag's name/label conflict with existing one","name":""}]}
```

**Comment by sapiens-sapide** [comment]
@iamdey : I'll fix the issue regarding the casse.  
Whereas, your second statement is not an issue. This is the way the API works for now: the `name` of the tag is the primary key used to embed tag's reference into objects. Consequently it must not change.

**Comment by iamdey** [comment]
Does this will change ?

Because what happens if I try to create a tag with a label which already exists when "sluggyfied" as a name ?

(do you remember what we have statued last time ?)

**Comment by sapiens-sapide** [comment]
I agree with you, this'll lead to a bad user experience. We need to discuss the point with @gdchamal because, for now, we decided to not take this usecase into account.
