### ISSUE TITLE
err 500 instead of 404 on patch message tags

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#749]
Err. when trying to patch tags on a message that doesn't exist:

PATCH /api/v2/messages/missing/tags

```
{"tags":["nouveau1"],"current_state":{}}
```

response:

```
{"errors":[{"code":500,"message":"not found","name":""}]}
```

**Comment by sapiens-sapide** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix tag label issue](https://trello.com/c/uMCWf8vg/12-fix-tag-label-issue)
