### ISSUE TITLE
Feature: mark as done

### ISSUE THREAD

**Issue by MathRobin** [CaliOpen/Caliopen#750]
Hi,

Have searched à bit but don't found if something similar has already been suggested / developed. Sorry if.

Something really important for me in my mail client is that I can mark a message as done. A great example is already present in Google Inbox. Without this, my daily work as freelance contractor would be a bit more annoying. Many mails, too many mails. Be able to mark it as done help me to have a quick and clear view of the rest to do.

Hope you will accept this feature.
"Merci à vous, bisous"

**Comment by iamdey** [comment]
In short term we will add the tag feature, you will be able to mark whatever you want (contact, message ...)

I suggest you to post your feature request on https://feedback.caliopen.org/ so we will be able to manage correctly the future of Caliopen ;)
