### ISSUE TITLE
UI does not report error when creating a tag into the popup

### ISSUE THREAD

**Issue by sapiens-sapide** [CaliOpen/Caliopen#765]
Steps to reproduce : 
* go to a contact card
* click `modify tags` in upper right menu
* enter a tag name that do not exist in your tags list but you know it will conflict with an existing one. For example : you have a tag with label `new tag` and you enter `new_tag`
* API will return an error, but UI does not handle it : spinner spins for ever.

**Comment by iamdey** [comment]
I close this since it happens only in develop and now fixed
