### ISSUE TITLE
close button is missing in notifications

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#860]
FF-dev@Linux:

![capture d ecran de 2018-04-09 15-55-24](https://user-images.githubusercontent.com/65737/38502024-a6c19dca-3c0e-11e8-8440-f07ab443227f.png)

chrome 64, sous ubuntu 17.10:

![https://framapic.org/0zarE7Bur9ue/VbjyMGG8YdB5.png](https://framapic.org/0zarE7Bur9ue/VbjyMGG8YdB5.png)

**Comment by myleneb** [comment]
fixed by https://github.com/CaliOpen/Caliopen/pull/873
