### ISSUE TITLE
Background image does not display in Firefox

### ISSUE THREAD

**Issue by MonsieurLanza** [CaliOpen/Caliopen#893]
While chrome displays the background image, Firefox is unable to display it. 
Error message is displayed after bg url fetched : "This file contains errors and cannot be displayed" 

![capture du 2018-05-03 12-15-38](https://user-images.githubusercontent.com/4181623/39571432-bf11199e-4ecb-11e8-9925-8590e21aa082.png)

**Comment by iamdey** [comment]
It looks like the library used to optimize the images in webpack doesn't work well

**Comment by MonsieurLanza** [comment]
Image is converted to google's WebP format and is no longer a JPG file.

**Comment by MonsieurLanza** [comment]
Fixed by d3770be
