### ISSUE TITLE
Attachment upload sometimes fail: no error message

### ISSUE THREAD

**Issue by VincentJ-Caliopen** [CaliOpen/Caliopen#896]
I upload my file, the little circle show that it is indeed being uploaded, then nothing. 
The attachment isn't uploaded, and there is no error message.
If I'm not careful I may send my message without knowing the attachment isn't there.

**Comment by VincentJ-Caliopen** [comment]
Similar issue:
I tried so send an attachment. The upload succeded and the sending took a while but succeded too. 
The recipient did receive the message and the attachment with it, but in my account the message doesn't display any attachment.

**Comment by iamdey** [comment]
I close this since it happened "sometimes" only.

If it goes up again here how we can deal with it:
* open a console (F12)
* try to poke stan directly 
* open a feedback issue instead and post js error if any, full screenshot with requests (if any) ...
