### ISSUE TITLE
"Unable to send the message": need more infos

### ISSUE THREAD

**Issue by VincentJ-Caliopen** [CaliOpen/Caliopen#897]
Sometimes I send a message and receive the error _Unable to send the message_ without further information about the problem.
Where is it coming from? The address is valid and the message is successfully sent if I wait a bit and retry.

**Comment by VincentJ-Caliopen** [comment]
Same issue when trying to save as a draft.

**Comment by VincentJ-Caliopen** [comment]
The _save_ error message can take up to 15 seconds to appear. 
I might believe my message was successfully saved and close the tab, with the error message appearing after that, while I'm in another tab.

**Comment by iamdey** [comment]
This should not happen, An error should be logged server side. It should be better now so I close this until this happens again.
