### ISSUE TITLE
Add failsafe on sending messages

### ISSUE THREAD

**Issue by VincentJ-Caliopen** [CaliOpen/Caliopen#901]
If I try to send a mail without a subject, the mail is sent. There should be a confirmation message asking if I'm sure I want to send without a subject.

If I try to send a mail without a recipient, nothing happens. There should be an error message telling me the recipient field is empty.

**Comment by iamdey** [comment]
@VincentJ-Caliopen 

An UX review should be done on this topic. /cc @Lauth0 

* we can add a confirm button when some regular fields are empty (subject/body) on the Send button
* if the participant field is empty the send button should be disabled (effectively and visually) so I think it should be enough. (except if there is a bug this condition)

**Comment by MonsieurLanza** [comment]
Send buttont is already disabled when no recipients are specified, but it is visually unclear.
