### ISSUE TITLE
wrong command: "copy to" saves a draft

### ISSUE THREAD

**Issue by VincentJ-Caliopen** [CaliOpen/Caliopen#903]
When I write a message in a discussion, _copy to_ saves a draft instead of copying the message.
As I understand it, the copy function is not available yet, so the button should be greyed out and noninteractive? Instead it is producing the wrong command.

![capture d ecran de 2018-05-03 15-06-04](https://user-images.githubusercontent.com/38942789/39578163-b5527af2-4ee3-11e8-9ca4-32c3293367e9.png)

**Comment by iamdey** [comment]
no more button copy to since total rewrite
