### ISSUE TITLE
New emails notifications not syncing correctly with timeline

### ISSUE THREAD

**Issue by sapiens-sapide** [CaliOpen/Caliopen#930]
In the morning, when I open a new browser window to check my emails in Caliopen (I'm already connected), I can see all my emails in timeline, including those arrived when window was closed.  

Few seconds later, I got a message saying "you have xxx new emails". But there is no new email in my timeline when I click this message !   

The problem is that frontend fetches the timeline, then it fetches notifications few seconds later. Notifications API responds with last xxx emails that arrived since last notifications check (as expected). But frontend doesn't check if messages listed in `/notifications` response are already in timeline.  
It should.

**Comment by iamdey** [comment]
We need to decide the responsibility of this, I though since the client fetched a message (or a list) this is not considered as new. So the notification does not exists at all.

But yeah you might be right, this may be the responsibility of the client to clean the notifications only if there is a user interaction

**Comment by iamdey** [comment]
here some changes in the langue of Moliere:

la notif des messages était utile dans l'ancienne TL. maintenant bp moins car messages regroupés par discussion, le message est aujourd'hui ne parait pas cohérent: « 110 nouveaux messages » alors que seulement 2 nvlles discussions apparaissent.

je propose simplement de mettre à jour la TL sans action particulières

dans les onglets j'hésite encore

**Comment by gdchamal** [comment]
I have this proposal for backend to reduce and structure better our current notifcations  
https://github.com/CaliOpen/Caliopen/pull/1404

**Comment by iamdey** [comment]
fix in #1417
