### ISSUE TITLE
action set_read on a message crash the page

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#938]
while scroll on a discussion, the action set_read is launched automatically then crash the page.
cf. https://feedback.caliopen.org/t/page-entierement-bleu-ciel/472

it also happen sometimes when clicking on mark as read/unread

```
TypeError: "e is undefined"
isParticipantUserhttps://alpha.caliopen.org/assets/app.5a9eb08a6f9598bff5bf.js:1:60509isMessageFromUserhttps://alpha.caliopen.org/assets/app.5a9eb08a6f9598bff5bf.js:1:61010
```

**Comment by iamdey** [comment]
It is actually due to backend when GET the message, the participants property is missing. cf. har file

[dey_mark-as-read_participants-removed.zip](https://github.com/CaliOpen/Caliopen/files/2031521/dey_mark-as-read_participants-removed.zip)

(import har in FF to see the requests)

First it looks like it happens on a discussion with multiple messages.
I have 9 messages. I can mark as read/unread the first message without any problem.
When reaching the second, after POST action it GET the message but participants is missing.
On an other discussion the first and the third messages seems to fail to set read/unread.

@sapiens-sapide you should be able to reproduce on alpha on your account

I don't see this happening on dev env.

**Comment by sapiens-sapide** [comment]
PR #971 adds a CLI that will permit to rebuild participants in db. That should fix this issue.
