### ISSUE TITLE
Upload a file in reply form (or delete it) results in bsod

### ISSUE THREAD

**Issue by MonsieurLanza** [CaliOpen/Caliopen#948]
State seems to be broken at some point : 
in src/modules/draftMessage/components/ReplyForm/presenter.jsx:164
```js
              disabled={isSending || !this.state.draft.body.length}
```
this.state.draft.body happens to be `undefined`.

**Comment by iamdey** [comment]
strange, do you know how to reproduce ?

**Comment by iamdey** [comment]
does this happen on production or on your env only ?

(I think we should not open issues that doesn't exist yet on stable branch, use trello instead for that kind of issues)

**Comment by MonsieurLanza** [comment]
I just reproduced it on production.

**Comment by iamdey** [comment]
i don't see Bsod now
